/**
 * ⚠️ TUDO "A VALIDAR". Valores copiados de docs/fase-0/doses-rascunho.md (rascunho feito de memória
 * pelo assistente, sem consulta às fontes). Servem só para desenvolver as telas e testar o programa.
 * O código da fonte é o PROVÁVEL; nenhum documento/página foi conferido.
 * Enquanto o status for 'A_VALIDAR', o programa não usa estes valores para corrigir o aluno.
 */

import type { Medicacao } from './tipos';

export const adrenalina: Medicacao = {
  id: 'adrenalina',
  nome: 'Adrenalina',
  secao: 6,
  classes: ['catecolaminas'],
  apresentacoes: [
    {
      id: 'ampola-1mg-ml',
      descricao: 'Ampola 1 mg/mL (1:1.000), 1 mL',
      forma: 'ampola',
      vias: ['EV', 'IO', 'IM', 'endotraqueal', 'inalatoria'],
      quantidade: { valor: 1, unidade: 'mg' },
      volumeMl: 1,
      concentracaoPorMl: { valor: 1, unidade: 'mg' },
      status: 'A_VALIDAR',
    },
  ],
  regras: [
    {
      id: 'pcr-crianca',
      indicacao: 'PCR',
      faixas: ['crianca', 'adolescente'],
      vias: ['EV', 'IO'],
      dose: { tipo: 'porKg', min: 0.01, max: 0.01, unidade: 'mg', por: 'dose' },
      doseMaxima: { valor: 1, unidade: 'mg', por: 'dose' },
      observacoes: '0,1 mL/kg da 1:10.000 (1 mL + 9 mL de SF), a cada 3–5 min.',
      fonte: { codigo: 'PALS' },
      status: 'A_VALIDAR',
    },
    {
      id: 'anafilaxia-crianca',
      indicacao: 'Anafilaxia',
      faixas: ['crianca'],
      vias: ['IM'],
      dose: { tipo: 'porKg', min: 0.01, max: 0.01, unidade: 'mg', por: 'dose' },
      doseMaxima: { valor: 0.3, unidade: 'mg', por: 'dose' },
      observacoes: 'Da 1:1.000 = 0,01 mL/kg. Repetir em 5–15 min.',
      fonte: { codigo: 'ASBAI' },
      status: 'A_VALIDAR',
    },
    {
      id: 'anafilaxia-adolescente',
      indicacao: 'Anafilaxia',
      faixas: ['adolescente'],
      vias: ['IM'],
      dose: { tipo: 'porKg', min: 0.01, max: 0.01, unidade: 'mg', por: 'dose' },
      doseMaxima: { valor: 0.5, unidade: 'mg', por: 'dose' },
      observacoes: 'Da 1:1.000 = 0,01 mL/kg. Repetir em 5–15 min.',
      fonte: { codigo: 'ASBAI' },
      status: 'A_VALIDAR',
    },
    {
      id: 'rn-reanimacao-ev',
      indicacao: 'Reanimação neonatal',
      faixas: ['RN'],
      vias: ['EV', 'IO'],
      dose: { tipo: 'porKg', min: 0.01, max: 0.03, unidade: 'mg', por: 'dose' },
      observacoes: '0,1–0,3 mL/kg da 1:10.000. Conferir valor da SBP 2022.',
      fonte: { codigo: 'NRP' },
      status: 'A_VALIDAR',
    },
    {
      id: 'rn-reanimacao-traqueal',
      indicacao: 'Reanimação neonatal',
      faixas: ['RN'],
      vias: ['endotraqueal'],
      dose: { tipo: 'porKg', min: 0.05, max: 0.1, unidade: 'mg', por: 'dose' },
      observacoes: '0,5–1 mL/kg da 1:10.000.',
      fonte: { codigo: 'NRP' },
      status: 'A_VALIDAR',
    },
    {
      id: 'pcr-traqueal',
      indicacao: 'PCR',
      faixas: ['crianca', 'adolescente'],
      vias: ['endotraqueal'],
      dose: { tipo: 'porKg', min: 0.1, max: 0.1, unidade: 'mg', por: 'dose' },
      fonte: { codigo: 'PALS' },
      status: 'A_VALIDAR',
    },
    {
      id: 'crupe-nebulizacao',
      indicacao: 'Laringite (crupe)',
      faixas: ['crianca', 'adolescente'],
      vias: ['inalatoria'],
      dose: { tipo: 'porKg', min: 0.5, max: 0.5, unidade: 'mg', por: 'dose' },
      doseMaxima: { valor: 5, unidade: 'mg', por: 'dose' },
      observacoes: '0,5 mL/kg da 1:1.000 pura na nebulização (máx 5 mL). Observar 2–4 h (rebote).',
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
    {
      id: 'choque-infusao',
      indicacao: 'Choque',
      faixas: ['crianca', 'adolescente'],
      vias: ['EV'],
      dose: { tipo: 'porKg', min: 0.05, max: 1, unidade: 'mcg', por: 'min' },
      fonte: { codigo: 'PALS' },
      status: 'A_VALIDAR',
    },
  ],
};

export const dipirona: Medicacao = {
  id: 'dipirona',
  nome: 'Dipirona',
  secao: 6,
  classes: ['pirazolonas', 'analgesicos'],
  apresentacoes: [
    {
      id: 'ampola-500mg-ml',
      descricao: 'Ampola 500 mg/mL, 2 mL',
      forma: 'ampola',
      vias: ['EV', 'IM'],
      quantidade: { valor: 1000, unidade: 'mg' },
      volumeMl: 2,
      concentracaoPorMl: { valor: 500, unidade: 'mg' },
      status: 'A_VALIDAR',
    },
    {
      id: 'sol-oral-50mg-ml',
      descricao: 'Solução oral 50 mg/mL, frasco 100 mL',
      forma: 'solucao-oral',
      vias: ['VO'],
      concentracaoPorMl: { valor: 50, unidade: 'mg' },
      volumeMl: 100,
      status: 'A_VALIDAR',
    },
    {
      id: 'comp-500mg',
      descricao: 'Comprimido 500 mg',
      forma: 'comprimido',
      vias: ['VO'],
      quantidade: { valor: 500, unidade: 'mg' },
      status: 'A_VALIDAR',
    },
    {
      id: 'gotas-500mg-ml',
      descricao: 'Gotas 500 mg/mL, frasco 20 mL',
      forma: 'gotas',
      vias: ['VO'],
      concentracaoPorMl: { valor: 500, unidade: 'mg' },
      volumeMl: 20,
      gotasPorMl: 20,
      status: 'A_VALIDAR',
    },
  ],
  regras: [
    {
      id: 'febre-dor-crianca',
      indicacao: 'Febre/dor',
      faixas: ['crianca'],
      vias: ['VO', 'EV', 'IM'],
      dose: { tipo: 'porKg', min: 10, max: 25, unidade: 'mg', por: 'dose' },
      intervalosHoras: [6],
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
    {
      id: 'febre-dor-adolescente',
      indicacao: 'Febre/dor',
      faixas: ['adolescente'],
      vias: ['VO', 'EV', 'IM'],
      dose: { tipo: 'fixa', min: 500, max: 1000, unidade: 'mg', por: 'dose' },
      doseMaxima: { valor: 4000, unidade: 'mg', por: 'dia' },
      intervalosHoras: [6],
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
  ],
  alertas: ['Bula: não usar em < 3 meses ou < 5 kg. EV com cautela (hipotensão).'],
};

export const ceftriaxona: Medicacao = {
  id: 'ceftriaxona',
  nome: 'Ceftriaxona',
  secao: 5,
  classes: ['cefalosporinas', 'betalactamicos'],
  receituario: 'antimicrobiano',
  concentracaoMaximaEV: {
    valor: 40,
    unidade: 'mg',
    fonte: { codigo: 'BULA' },
    status: 'A_VALIDAR',
    observacao: 'Valor de exemplo para o alerta funcionar; conferir na bula/rotina.',
  },
  apresentacoes: [
    {
      id: 'fa-500mg',
      descricao: 'Frasco-ampola 500 mg (pó)',
      forma: 'frasco-ampola-po',
      vias: ['EV', 'IM'],
      quantidade: { valor: 500, unidade: 'mg' },
      status: 'A_VALIDAR',
    },
    {
      id: 'fa-1g',
      descricao: 'Frasco-ampola 1 g (pó)',
      forma: 'frasco-ampola-po',
      vias: ['EV', 'IM'],
      quantidade: { valor: 1000, unidade: 'mg' },
      status: 'A_VALIDAR',
    },
  ],
  regras: [
    {
      id: 'geral-crianca',
      indicacao: 'Infecção bacteriana',
      faixas: ['crianca', 'adolescente'],
      vias: ['EV', 'IM'],
      dose: { tipo: 'porKg', min: 50, max: 75, unidade: 'mg', por: 'dia' },
      doseMaxima: { valor: 2000, unidade: 'mg', por: 'dia' },
      intervalosHoras: [12, 24],
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
    {
      id: 'rn-oftalmia',
      indicacao: 'Oftalmia gonocócica',
      faixas: ['RN'],
      vias: ['IM', 'EV'],
      dose: { tipo: 'porKg', min: 25, max: 50, unidade: 'mg', por: 'dose' },
      doseMaxima: { valor: 125, unidade: 'mg', por: 'dose' },
      observacoes: 'Dose única.',
      fonte: { codigo: 'AAP' },
      status: 'A_VALIDAR',
    },
    {
      id: 'meningite-crianca',
      indicacao: 'Meningite',
      faixas: ['crianca', 'adolescente'],
      vias: ['EV'],
      dose: { tipo: 'porKg', min: 100, max: 100, unidade: 'mg', por: 'dia' },
      doseMaxima: { valor: 4000, unidade: 'mg', por: 'dia' },
      intervalosHoras: [12, 24],
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
  ],
  alertas: [
    'RN: evitar em hiperbilirrubinemia/prematuro e NUNCA com cálcio EV em ≤ 28 dias.',
  ],
};

/** Exemplo de regra que muda com a idade em dias (12/12h até 7 dias de vida, 8/8h depois). */
export const penicilinaCristalina: Medicacao = {
  id: 'penicilina-cristalina',
  nome: 'Penicilina G cristalina',
  secao: 5,
  classes: ['penicilinas', 'betalactamicos'],
  receituario: 'antimicrobiano',
  apresentacoes: [
    {
      id: 'fa-1milhao',
      descricao: 'Frasco-ampola 1.000.000 UI (pó)',
      forma: 'frasco-ampola-po',
      vias: ['EV', 'IM'],
      quantidade: { valor: 1_000_000, unidade: 'UI' },
      status: 'A_VALIDAR',
    },
    {
      id: 'fa-5milhoes',
      descricao: 'Frasco-ampola 5.000.000 UI (pó)',
      forma: 'frasco-ampola-po',
      vias: ['EV', 'IM'],
      quantidade: { valor: 5_000_000, unidade: 'UI' },
      status: 'A_VALIDAR',
    },
  ],
  regras: [
    {
      id: 'sifilis-rn-ate-7d',
      indicacao: 'Sífilis congênita / neurossífilis',
      faixas: ['RN'],
      condicoes: { idadeDias: { ate: 7 } },
      vias: ['EV'],
      dose: { tipo: 'porKg', min: 50_000, max: 50_000, unidade: 'UI', por: 'dose' },
      intervalosHoras: [12],
      observacoes: 'Por 10 dias.',
      fonte: { codigo: 'MS' },
      status: 'A_VALIDAR',
    },
    {
      id: 'sifilis-rn-apos-7d',
      indicacao: 'Sífilis congênita / neurossífilis',
      faixas: ['RN'],
      condicoes: { idadeDias: { de: 7 } },
      vias: ['EV'],
      dose: { tipo: 'porKg', min: 50_000, max: 50_000, unidade: 'UI', por: 'dose' },
      intervalosHoras: [8],
      observacoes: 'Completar 10 dias de tratamento.',
      fonte: { codigo: 'MS' },
      status: 'A_VALIDAR',
    },
    {
      id: 'infeccao-grave-crianca',
      indicacao: 'Infecção grave / meningite',
      faixas: ['crianca', 'adolescente'],
      vias: ['EV'],
      dose: { tipo: 'porKg', min: 250_000, max: 400_000, unidade: 'UI', por: 'dia' },
      doseMaxima: { valor: 24_000_000, unidade: 'UI', por: 'dia' },
      intervalosHoras: [4, 6],
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
  ],
};

/** Oral, para a receita de alta. Dose do doses-rascunho.md (item 32), A VALIDAR. */
export const prednisolona: Medicacao = {
  id: 'prednisolona',
  nome: 'Prednisolona',
  secao: 6,
  classes: ['corticoides'],
  receituario: 'simples',
  apresentacoes: [
    {
      id: 'sol-oral-3mg-ml',
      descricao: 'Solução oral 3 mg/mL, frasco 60 mL',
      forma: 'solucao-oral',
      vias: ['VO'],
      concentracaoPorMl: { valor: 3, unidade: 'mg' },
      volumeMl: 60,
      status: 'A_VALIDAR',
    },
    {
      id: 'sol-oral-1mg-ml',
      descricao: 'Solução oral 1 mg/mL, frasco 100 mL',
      forma: 'solucao-oral',
      vias: ['VO'],
      concentracaoPorMl: { valor: 1, unidade: 'mg' },
      volumeMl: 100,
      status: 'A_VALIDAR',
    },
  ],
  regras: [
    {
      id: 'asma-crianca',
      indicacao: 'Asma (crise)',
      faixas: ['crianca', 'adolescente'],
      vias: ['VO'],
      dose: { tipo: 'porKg', min: 1, max: 2, unidade: 'mg', por: 'dia' },
      doseMaxima: { valor: 60, unidade: 'mg', por: 'dia' },
      intervalosHoras: [24],
      observacoes: 'Por 3–5 dias. Rascunho diz "máx 40–60 mg/dia": usado 60 até conferir.',
      fonte: { codigo: 'SBP' },
      status: 'A_VALIDAR',
    },
  ],
};

/** Oral, para a receita de alta. Só apresentações (sem dose no rascunho): A VALIDAR. */
export const amoxicilina: Medicacao = {
  id: 'amoxicilina',
  nome: 'Amoxicilina',
  secao: 5,
  classes: ['penicilinas', 'betalactamicos'],
  receituario: 'antimicrobiano',
  apresentacoes: [
    {
      id: 'susp-250mg-5ml',
      descricao: 'Suspensão oral 250 mg/5 mL, frasco 150 mL',
      forma: 'solucao-oral',
      vias: ['VO'],
      concentracaoPorMl: { valor: 50, unidade: 'mg' },
      volumeMl: 150,
      status: 'A_VALIDAR',
    },
    {
      id: 'comp-500mg',
      descricao: 'Cápsula 500 mg',
      forma: 'comprimido',
      vias: ['VO'],
      quantidade: { valor: 500, unidade: 'mg' },
      status: 'A_VALIDAR',
    },
  ],
  regras: [],
};

export const MEDICACOES_EXEMPLO: readonly Medicacao[] = [
  adrenalina,
  dipirona,
  ceftriaxona,
  penicilinaCristalina,
  prednisolona,
  amoxicilina,
];
