/**
 * Exame físico de doenças comuns na atenção básica (otoscopia, oroscopia, pele, hidratação,
 * sinais meníngeos, ausculta) — DADOS.
 * ⚠️ TUDO "A VALIDAR": textos do assistente (SBP, MS/AIDPI, Nelson). Desenhos em src/ilustracoes/.
 */

import type { StatusValidacao } from '../medicacoes/tipos';

const AV: StatusValidacao = 'A_VALIDAR';

export type SistemaExame = 'ouvido' | 'garganta' | 'pele' | 'hidratacao' | 'respiracao' | 'meningeo';

export const NOME_SISTEMA: Record<SistemaExame, string> = {
  ouvido: '👂 Otoscopia',
  garganta: '👄 Oroscopia',
  pele: '🖐️ Pele e exantemas',
  hidratacao: '💧 Hidratação',
  respiracao: '🫁 Respiração',
  meningeo: '🧠 Sinais meníngeos',
};

export interface AchadoExame {
  id: string;
  sistema: SistemaExame;
  nome: string;
  oQueSeVe: string;
  significado: string;
  conduta: string;
  /** Desenho: tipo + achado (src/ilustracoes/atencao-basica/). */
  desenho?: { tipo: 'otoscopia' | 'garganta' | 'pele' | 'crianca' | 'prega' | 'respiracao' | 'meningeo'; achado: string };
  /** Problema da aba "Receitas" ligado a este achado. */
  receitaId?: string;
  status: StatusValidacao;
}

export const ACHADOS_ATENCAO_BASICA: readonly AchadoExame[] = [
  // ---- OUVIDO ----
  {
    id: 'mt-normal',
    sistema: 'ouvido',
    nome: 'Membrana timpânica normal',
    oQueSeVe: 'Membrana cinza-perolada, translúcida, com o cabo do martelo visível e o triângulo luminoso (reflexo da luz) na parte anteroinferior.',
    significado: 'Normal.',
    conduta: 'Nada a fazer.',
    desenho: { tipo: 'otoscopia', achado: 'normal' },
    status: AV,
  },
  {
    id: 'oma',
    sistema: 'ouvido',
    nome: 'Otite média aguda',
    oQueSeVe: 'Membrana ABAULADA, vermelha/amarelada e opaca; cabo do martelo e triângulo luminoso não aparecem.',
    significado: 'Pus na orelha média sob pressão. O abaulamento é o sinal mais importante.',
    conduta: 'Analgesia sempre; antibiótico conforme idade e gravidade (ver receita).',
    desenho: { tipo: 'otoscopia', achado: 'oma' },
    receitaId: 'oma',
    status: AV,
  },
  {
    id: 'ome',
    sistema: 'ouvido',
    nome: 'Otite média com efusão (secretora)',
    oQueSeVe: 'Membrana retraída, cor âmbar, com nível líquido e bolhas de ar atrás dela; sem abaulamento; criança sem febre nem dor.',
    significado: 'Líquido na orelha média sem infecção aguda (comum depois de OMA ou resfriado).',
    conduta: 'Não usar antibiótico; observar por até 3 meses; avaliar audição se persistir.',
    desenho: { tipo: 'otoscopia', achado: 'ome' },
    status: AV,
  },
  {
    id: 'otite-externa',
    sistema: 'ouvido',
    nome: 'Otite externa',
    oQueSeVe: 'Conduto inchado e vermelho, com secreção; dor forte ao puxar a orelha ou apertar o trago. Membrana difícil de ver.',
    significado: 'Infecção da pele do conduto (piscina, cotonete).',
    conduta: 'Gotas otológicas com antibiótico (± corticoide) — A VALIDAR; analgesia; evitar água no ouvido.',
    desenho: { tipo: 'otoscopia', achado: 'otite-externa' },
    status: AV,
  },
  {
    id: 'perfuracao',
    sistema: 'ouvido',
    nome: 'Perfuração com otorreia',
    oQueSeVe: 'Secreção purulenta no conduto e um orifício na membrana; a dor melhorou quando começou a escorrer.',
    significado: 'OMA que perfurou (a pressão aliviou).',
    conduta: 'Antibiótico oral (± gotas sem ototoxicidade — A VALIDAR); manter o ouvido seco; reavaliar a cicatrização.',
    desenho: { tipo: 'otoscopia', achado: 'perfuracao' },
    status: AV,
  },
  // ---- GARGANTA ----
  {
    id: 'garganta-normal',
    sistema: 'garganta',
    nome: 'Orofaringe normal',
    oQueSeVe: 'Amígdalas pequenas e rosadas, úvula central, palato sem lesões.',
    significado: 'Normal.',
    conduta: 'Nada a fazer.',
    desenho: { tipo: 'garganta', achado: 'normal' },
    status: AV,
  },
  {
    id: 'faringite-viral',
    sistema: 'garganta',
    nome: 'Faringite viral',
    oQueSeVe: 'Faringe e amígdalas avermelhadas, sem pus, com coriza, tosse e rouquidão junto.',
    significado: 'A grande maioria das dores de garganta é viral.',
    conduta: 'Sintomáticos; sem antibiótico.',
    desenho: { tipo: 'garganta', achado: 'faringite-viral' },
    receitaId: 'resfriado',
    status: AV,
  },
  {
    id: 'amigdalite-bacteriana',
    sistema: 'garganta',
    nome: 'Faringoamigdalite estreptocócica',
    oQueSeVe: 'Amígdalas aumentadas e vermelhas com placas de pus, petéquias no palato, ínguas no pescoço; febre alta, sem tosse nem coriza.',
    significado: 'Estreptococo do grupo A (mais em 5 a 15 anos). Escore de Centor/McIsaac ajuda; teste rápido confirma.',
    conduta: 'Antibiótico (amoxicilina 10 dias ou penicilina benzatina) — ver receita.',
    desenho: { tipo: 'garganta', achado: 'amigdalite-bacteriana' },
    receitaId: 'faringoamigdalite',
    status: AV,
  },
  {
    id: 'herpangina',
    sistema: 'garganta',
    nome: 'Herpangina (coxsackie)',
    oQueSeVe: 'Pequenas vesículas e úlceras com halo vermelho no palato mole, úvula e pilares; febre e recusa alimentar.',
    significado: 'Enterovírus; se houver lesões em mãos e pés, é a doença mão-pé-boca.',
    conduta: 'Analgesia, líquidos frios; vigiar desidratação.',
    desenho: { tipo: 'garganta', achado: 'herpangina' },
    status: AV,
  },
  {
    id: 'mononucleose',
    sistema: 'garganta',
    nome: 'Mononucleose infecciosa',
    oQueSeVe: 'Amígdalas muito aumentadas com placas acinzentadas, gânglios no pescoço todo, cansaço; às vezes baço palpável.',
    significado: 'Vírus Epstein-Barr (mais em adolescentes).',
    conduta: 'Sintomáticos; NÃO dar amoxicilina (rash); evitar esportes de contato por semanas (baço).',
    desenho: { tipo: 'garganta', achado: 'mononucleose' },
    status: AV,
  },
  {
    id: 'lingua-framboesa',
    sistema: 'garganta',
    nome: 'Língua em framboesa (escarlatina)',
    oQueSeVe: 'Língua vermelha com papilas saltadas; antes pode ter uma camada branca ("morango branco").',
    significado: 'Escarlatina (toxina do estreptococo) — também na doença de Kawasaki.',
    conduta: 'Escarlatina: tratar como faringoamigdalite estreptocócica.',
    desenho: { tipo: 'garganta', achado: 'framboesa' },
    receitaId: 'faringoamigdalite',
    status: AV,
  },
  // ---- PELE ----
  {
    id: 'sarampo',
    sistema: 'pele',
    nome: 'Sarampo',
    oQueSeVe: 'Manchas vermelhas que se juntam, começando atrás das orelhas e no rosto e descendo; febre alta, tosse, coriza e conjuntivite; manchas de Koplik na boca.',
    significado: 'Doença de notificação compulsória imediata; prevenível por vacina.',
    conduta: 'Isolamento respiratório, notificação imediata, vitamina A (A VALIDAR), conferir vacinação dos contatos.',
    desenho: { tipo: 'pele', achado: 'sarampo' },
    status: AV,
  },
  {
    id: 'varicela',
    sistema: 'pele',
    nome: 'Varicela (catapora)',
    oQueSeVe: 'Lesões em vários estágios ao mesmo tempo: manchas, pápulas, vesículas ("gota de orvalho") e crostas; coça; começa no tronco.',
    significado: 'Vírus varicela-zóster; contagiosa até todas virarem crosta.',
    conduta: 'Sintomáticos (sem AAS, sem ibuprofeno — A VALIDAR); unhas curtas; aciclovir em grupos de risco.',
    desenho: { tipo: 'pele', achado: 'varicela' },
    status: AV,
  },
  {
    id: 'escarlatina',
    sistema: 'pele',
    nome: 'Escarlatina',
    oQueSeVe: 'Pele vermelha e áspera como lixa, mais forte nas dobras (sinal de Pastia), palidez ao redor da boca; dor de garganta e febre.',
    significado: 'Estreptococo do grupo A produtor de toxina.',
    conduta: 'Antibiótico como na faringoamigdalite estreptocócica.',
    desenho: { tipo: 'pele', achado: 'escarlatina' },
    receitaId: 'faringoamigdalite',
    status: AV,
  },
  {
    id: 'roseola',
    sistema: 'pele',
    nome: 'Exantema súbito (roséola)',
    oQueSeVe: 'Lactente com 3 dias de febre alta e bom estado; quando a febre some, aparecem manchinhas rosadas no tronco.',
    significado: 'Herpesvírus 6/7; benigna.',
    conduta: 'Tranquilizar; antitérmico durante a febre.',
    desenho: { tipo: 'pele', achado: 'roseola' },
    status: AV,
  },
  {
    id: 'impetigo',
    sistema: 'pele',
    nome: 'Impetigo',
    oQueSeVe: 'Lesões com crostas cor de mel ao redor do nariz e da boca.',
    significado: 'Infecção superficial por estafilococo/estreptococo.',
    conduta: 'Limpeza e antibiótico tópico se localizado (ver receita).',
    desenho: { tipo: 'pele', achado: 'impetigo' },
    receitaId: 'impetigo',
    status: AV,
  },
  {
    id: 'escabiose',
    sistema: 'pele',
    nome: 'Escabiose',
    oQueSeVe: 'Pápulas escoriadas e pequenos túneis entre os dedos, punhos, axilas e cintura; coceira pior à noite; família com o mesmo quadro.',
    significado: 'Ácaro Sarcoptes scabiei.',
    conduta: 'Permetrina 5% em todos da casa (ver receita).',
    desenho: { tipo: 'pele', achado: 'escabiose' },
    receitaId: 'escabiose',
    status: AV,
  },
  {
    id: 'molusco',
    sistema: 'pele',
    nome: 'Molusco contagioso',
    oQueSeVe: 'Pápulas peroladas, cor da pele, com uma depressão no centro (umbilicadas).',
    significado: 'Poxvírus; some sozinho em meses.',
    conduta: 'Observar; tratar se muitas lesões ou incômodo (curetagem, outros — A VALIDAR).',
    desenho: { tipo: 'pele', achado: 'molusco' },
    status: AV,
  },
  {
    id: 'dermatite-atopica',
    sistema: 'pele',
    nome: 'Dermatite atópica',
    oQueSeVe: 'Placas vermelhas, ásperas, com pele grossa e marcas de coçar nas dobras (cotovelos, joelhos); pele seca.',
    significado: 'Doença crônica da barreira da pele; associa-se a asma e rinite.',
    conduta: 'Hidratação diária da pele, banho morno e curto; corticoide tópico nas crises (A VALIDAR).',
    desenho: { tipo: 'pele', achado: 'dermatite-atopica' },
    status: AV,
  },
  {
    id: 'urticaria',
    sistema: 'pele',
    nome: 'Urticária',
    oQueSeVe: 'Placas elevadas, que coçam, mudam de lugar em horas (cada uma dura menos de 24 h).',
    significado: 'Alergia, infecção viral ou sem causa definida. Com falta de ar, inchaço de lábios ou vômitos: anafilaxia!',
    conduta: 'Anti-histamínico (A VALIDAR); afastar o desencadeante; anafilaxia = adrenalina IM.',
    desenho: { tipo: 'pele', achado: 'urticaria' },
    status: AV,
  },
  {
    id: 'tinha',
    sistema: 'pele',
    nome: 'Tinha do corpo',
    oQueSeVe: 'Lesão em anel, com borda vermelha descamativa que cresce e centro mais claro.',
    significado: 'Fungo (dermatófito), comum com animais de estimação.',
    conduta: 'Antifúngico tópico por 2 a 4 semanas (A VALIDAR).',
    desenho: { tipo: 'pele', achado: 'tinha' },
    status: AV,
  },
  // ---- HIDRATAÇÃO ----
  {
    id: 'hidratado',
    sistema: 'hidratacao',
    nome: 'Sem desidratação',
    oQueSeVe: 'Alerta, olhos normais, lágrimas presentes, boca e língua úmidas, bebe normalmente; sinal da prega desaparece rápido.',
    significado: 'Plano A (MS).',
    conduta: 'Tratamento em casa: SRO após cada evacuação, alimentação habitual, zinco.',
    desenho: { tipo: 'crianca', achado: 'hidratada' },
    receitaId: 'diarreia',
    status: AV,
  },
  {
    id: 'desidratado',
    sistema: 'hidratacao',
    nome: 'Desidratação',
    oQueSeVe: 'Irritado, olhos fundos, sem lágrimas, boca seca, bebe com avidez; sinal da prega desaparece lentamente.',
    significado: 'Plano B (MS): reidratação oral na unidade de saúde.',
    conduta: 'SRO 50 a 100 mL/kg em 4 a 6 h na unidade, reavaliando (A VALIDAR).',
    desenho: { tipo: 'crianca', achado: 'desidratada' },
    status: AV,
  },
  {
    id: 'prega-lenta',
    sistema: 'hidratacao',
    nome: 'Sinal da prega lento',
    oQueSeVe: 'Ao pinçar a pele do abdome, a prega demora mais de 2 segundos para desaparecer.',
    significado: 'Desidratação grave (com outros sinais: letargia, não consegue beber) → Plano C.',
    conduta: 'Hidratação venosa (Plano C) — ver Passo a passo "Desidratação grave".',
    desenho: { tipo: 'prega', achado: 'lenta' },
    status: AV,
  },
  // ---- RESPIRAÇÃO ----
  {
    id: 'taquipneia',
    sistema: 'respiracao',
    nome: 'Respiração rápida',
    oQueSeVe: 'Contar 1 minuto inteiro: FR ≥ 50 (2–11 meses) ou ≥ 40 (1–4 anos) — limites do AIDPI, A VALIDAR.',
    significado: 'Sinal de pneumonia na criança com tosse.',
    conduta: 'Com tosse e respiração rápida sem sinais de gravidade: pneumonia → antibiótico oral (A VALIDAR).',
    desenho: { tipo: 'respiracao', achado: 'taquipneia' },
    status: AV,
  },
  {
    id: 'tiragem',
    sistema: 'respiracao',
    nome: 'Tiragem subcostal',
    oQueSeVe: 'A parte de baixo do tórax afunda quando a criança inspira.',
    significado: 'Sinal de gravidade (pneumonia grave no AIDPI).',
    conduta: 'Encaminhar com urgência; primeira dose de antibiótico e oxigênio se disponível.',
    desenho: { tipo: 'respiracao', achado: 'tiragem' },
    status: AV,
  },
  // ---- MENÍNGEOS ----
  {
    id: 'rigidez-nuca',
    sistema: 'meningeo',
    nome: 'Rigidez de nuca',
    oQueSeVe: 'Ao fletir o pescoço (queixo no peito), há resistência e dor.',
    significado: 'Irritação meníngea (meningite, hemorragia). No lactente pequeno pode faltar: olhe a fontanela e o estado geral.',
    conduta: 'Urgência: encaminhar; antibiótico precoce se suspeita de meningite bacteriana.',
    desenho: { tipo: 'meningeo', achado: 'nuca' },
    status: AV,
  },
  {
    id: 'kernig',
    sistema: 'meningeo',
    nome: 'Sinal de Kernig',
    oQueSeVe: 'Deitado, com quadril e joelho a 90°, a extensão do joelho provoca dor e resistência.',
    significado: 'Irritação meníngea.',
    conduta: 'Como na rigidez de nuca.',
    desenho: { tipo: 'meningeo', achado: 'kernig' },
    status: AV,
  },
  {
    id: 'brudzinski',
    sistema: 'meningeo',
    nome: 'Sinal de Brudzinski',
    oQueSeVe: 'Ao fletir o pescoço, a criança dobra os quadris e os joelhos sozinha.',
    significado: 'Irritação meníngea.',
    conduta: 'Como na rigidez de nuca.',
    desenho: { tipo: 'meningeo', achado: 'brudzinski' },
    status: AV,
  },
];
